version: '2'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      JUPYTER_TOKEN: "effort"
    ports: 
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
